all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-44-244-220-28.us-west-2.compute.amazonaws.com

        server-two:
          ansible_host: ec2-34-216-26-132.us-west-2.compute.amazonaws.com
