- name: Configure web servers
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        mode: '0755'
    - name: copy nginx conf file to server
      copy:
        src: file/nginx.conf
        dest: /etc/nginx 
    - name: create link to nginx config file to enable it
      ansible.builtin.file:
       src: /etc/nginx/sites-available/nginx.conf
       dest: /etc/nginx/sites-enabled/nginx.conf
       state: link
    
    - name: Generate index.html file from template
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: /web/html/index.html
        owner: bin
        group: wheel
        mode: '0644'
    - name: reload nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
