- name: Configure web servers
  tasks:
    - name: Install nginx
      ansbile.builtin.apt:
        name: nginx
        state: present
    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        mode: '0755'
    - name: copy nginx conf file to server
      copy:
        src: file/nginx.conf
        dest: /etc/nginx 
    - name: create link to nginx config file to enable it
      ansible.builtin.file:
       src: /etc/nginx/sites-available/nginx.conf
       dest: /etc/nginx/sites-enabled/nginx.conf
       state: link
    - name: Generate index.html file from template
    - name: reload nginx service
      ansible.bulitin.service:
        name: nginx
        state: reloaded
